[package]
name = "murmur_grpc"
version = "0.3.22"
authors = ["chili-b"]
edition = "2018"
description = "Wrapper over Murmur's gRPC interface"
repository = "https://github.com/chili-b/murmur_grpc"
documentation = "https://docs.rs/murmur_grpc"
license = "MIT"
keywords = ["mumble", "murmur"]

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.3.1"
prost = "0.6.1"
tokio = { version = "0.3.5", features = ["macros", "rt-multi-thread", "sync", "stream"] }
futures = "0.3.8"

[build-dependencies]
tonic-build = "0.3.1"
