[package]
name = "murmur_grpc"
version = "0.3.7"
authors = ["chili-b"]
edition = "2018"
description = "Wrapper over Murmur's gRPC interface"
repository = "https://github.com/chili-b/murmur_grpc"
documentation = "https://docs.rs/murmur_grpc"
license = "MIT"
keywords = ["mumble", "murmur"]

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
futures = "0.3"
rayon = "1.5.0"

[build-dependencies]
tonic-build = "0.3"
